// @ts-nocheck
"use client";

import { useState } from "react";
import {
  Artifact,
  ArtifactHeader,
  ArtifactTitle,
  ArtifactDescription,
  ArtifactContent,
  ArtifactActions,
  ArtifactAction,
  ArtifactClose,
} from "@/components/ai-elements/artifact";
import {
  CodeBlock,
  CodeBlockHeader,
  CodeBlockTitle,
  CodeBlockContent,
  CodeBlockCopyButton,
} from "@/components/ai-elements/code-block";
import {
  EnvironmentVariables,
  EnvironmentVariablesHeader,
  EnvironmentVariablesTitle,
  EnvironmentVariablesContent,
  EnvironmentVariable,
  EnvironmentVariableName,
  EnvironmentVariableValue,
  EnvironmentVariableCopyButton,
  EnvironmentVariableGroup,
  EnvironmentVariableRequired,
} from "@/components/ai-elements/environment-variables";
import {
  SchemaDisplay,
  SchemaDisplayHeader,
  SchemaDisplayMethod,
  SchemaDisplayPath,
  SchemaDisplayDescription,
  SchemaDisplayContent,
  SchemaDisplayParameter,
  SchemaDisplayParameters,
  SchemaDisplayProperty,
  SchemaDisplayRequest,
  SchemaDisplayResponse,
  SchemaDisplayBody,
  SchemaDisplayExample,
} from "@/components/ai-elements/schema-display";
import {
  Commit,
  CommitHeader,
  CommitHash,
  CommitMessage,
  CommitMetadata,
  CommitInfo,
  CommitAuthor,
  CommitAuthorAvatar,
  CommitTimestamp,
  CommitActions,
  CommitCopyButton,
  CommitContent,
  CommitFiles,
  CommitFile,
} from "@/components/ai-elements/commit";
import {
  WebPreview,
  WebPreviewNavigation,
  WebPreviewNavigationButton,
  WebPreviewUrl,
  WebPreviewBody,
} from "@/components/ai-elements/web-preview";
import { JSXPreview, JSXPreviewContent, JSXPreviewError } from "@/components/ai-elements/jsx-preview";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  CopyIcon,
  DownloadIcon,
  PlayIcon,
  RefreshCwIcon,
  ShareIcon,
  XIcon,
  EyeIcon,
  CodeIcon,
  FileTextIcon,
  GitBranchIcon,
  BoxIcon,
  SparklesIcon,
  ExternalLinkIcon,
  GlobeIcon,
} from "lucide-react";

const SAMPLE_CODE = `# Dijkstra's Algorithm implementation
import heapq

def dijkstra(graph, start):
    distances = {node: float('inf') for node in graph}
    distances[start] = 0
    heap = [(0, start)]
    visited = set()
    
    while heap:
        current_distance, current_node = heapq.heappop(heap)
        if current_node in visited:
            continue
        visited.add(current_node)
        
        for neighbor, weight in graph[current_node].items():
            distance = current_distance + weight
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(heap, (distance, neighbor))
    
    return distances

# Example graph
graph = {
    'A': {'B': 1, 'C': 4},
    'B': {'A': 1, 'C': 2, 'D': 5},
    'C': {'A': 4, 'B': 2, 'D': 1},
    'D': {'B': 5, 'C': 1}
}

print(dijkstra(graph, 'A'))`;

const SAMPLE_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Generated UI</title>
  <style>
    body { font-family: system-ui; background: #0a0a0a; color: #fafafa; padding: 24px; }
    .card { background: #18181b; border: 1px solid #27272a; border-radius: 12px; padding: 16px; }
    button { background: #14b8a6; color: white; border: none; padding: 8px 16px; border-radius: 8px; }
  </style>
</head>
<body>
  <div class="card">
    <h2>Hello from agenticOS</h2>
    <p>This artifact was generated by the agent.</p>
    <button>Click me</button>
  </div>
</body>
</html>`;

const SAMPLE_DOC = `# agenticOS — Architecture Overview

## Components

1. **Chat** — Streaming AI conversation with chain-of-thought visualization
2. **Voice** — Real-time speech-to-text and text-to-speech
3. **Code** — Sandboxed code execution with terminal output
4. **Workflow** — Visual agent graph with parallel tool execution
5. **Artifacts** — Generated code, HTML, and documents

## API

- \`POST /api/chat\` — Streaming NDJSON response
- \`GET /api/sessions\` — List user sessions
- \`POST /api/messages\` — Persist a message

## Models

- MiniMax M2 — Default fast model
- MiniMax M2 Reasoning — Extended chain-of-thought
`;

const ENV_VARS = [
  { name: "DATABASE_URL", value: "postgresql://neondb_owner:npg_***@ep-damp-pine.aws.neon.tech/neondb" },
  { name: "DIRECT_URL", value: "postgresql://neondb_owner:npg_***@ep-damp-pine.aws.neon.tech/neondb" },
  { name: "MINIMAX_API_KEY", value: "sk-cp-***REDACTED***" },
  { name: "JWT_SECRET", value: "agentic-os-secret-change-in-production" },
];

const COMMITS = [
  {
    hash: "12f53e8",
    message: "Mobile UI: teal/coral palette, fonts, sidebar drawer, settings panel",
    author: "Akashdeep Mahalaz",
    initials: "AM",
    time: "2 hours ago",
    files: [
      { name: "app/globals.css", additions: 145, deletions: 12 },
      { name: "components/chat/sidebar.tsx", additions: 78, deletions: 0 },
      { name: "app/(app)/page.tsx", additions: 32, deletions: 18 },
    ],
  },
  {
    hash: "f8ad7d7",
    message: "ChainOfThought pattern with icons, search results, proper AI Elements",
    author: "Akashdeep Mahalaz",
    initials: "AM",
    time: "4 hours ago",
    files: [
      { name: "components/chat/chat-container.tsx", additions: 92, deletions: 30 },
    ],
  },
  {
    hash: "8c8ff1f",
    message: "AI Elements: all 48 components, full UI with conversation/message/reasoning",
    author: "Akashdeep Mahalaz",
    initials: "AM",
    time: "yesterday",
    files: [
      { name: "components/ai-elements/", additions: 4320, deletions: 0 },
    ],
  },
];

export default function ArtifactsPage() {
  const [tab, setTab] = useState<"code" | "html" | "doc">("code");
  const [showEnv, setShowEnv] = useState(false);

  return (
    <div className="flex flex-col h-full bg-background overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-3 md:px-5 h-12 border-b border-border flex-shrink-0 bg-background/95 backdrop-blur-md z-20">
        <div className="flex items-center gap-2 min-w-0">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-teal to-coral flex items-center justify-center text-white">
            <BoxIcon size={14} />
          </div>
          <h1 className="text-sm font-semibold tracking-tight font-space-grotesk">Artifacts</h1>
        </div>
        <div className="flex items-center gap-1.5">
          <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
            <DownloadIcon size={15} />
          </Button>
          <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
            <ShareIcon size={15} />
          </Button>
        </div>
      </header>

      <div className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto p-3 md:p-5 space-y-5 pb-32">
          {/* Active artifact using AI Elements Artifact component */}
          <Artifact className="rounded-2xl border border-border bg-card overflow-hidden">
            <ArtifactHeader className="p-4 border-b border-border">
              <div className="min-w-0 flex-1">
                <ArtifactTitle className="text-base font-semibold tracking-tight font-space-grotesk">
                  Generated Code
                </ArtifactTitle>
                <ArtifactDescription className="text-xs text-muted-foreground mt-0.5">
                  Updated 1 minute ago · {SAMPLE_CODE.split("\n").length} lines
                </ArtifactDescription>
              </div>
              <ArtifactActions>
                <ArtifactAction tooltip="Run code">
                  <PlayIcon size={15} />
                </ArtifactAction>
                <ArtifactAction tooltip="Copy">
                  <CopyIcon size={15} />
                </ArtifactAction>
                <ArtifactAction tooltip="Regenerate">
                  <RefreshCwIcon size={15} />
                </ArtifactAction>
                <ArtifactAction tooltip="Download">
                  <DownloadIcon size={15} />
                </ArtifactAction>
                <ArtifactClose>
                  <XIcon size={15} />
                </ArtifactClose>
              </ArtifactActions>
            </ArtifactHeader>
            <ArtifactContent className="p-0">
              <Tabs value={tab} onValueChange={(v) => setTab(v as any)}>
                <TabsList className="m-3 mb-0">
                  <TabsTrigger value="code" className="text-xs">
                    <CodeIcon size={12} className="mr-1.5" />
                    Code
                  </TabsTrigger>
                  <TabsTrigger value="html" className="text-xs">
                    <GlobeIcon size={12} className="mr-1.5" />
                    HTML
                  </TabsTrigger>
                  <TabsTrigger value="doc" className="text-xs">
                    <FileTextIcon size={12} className="mr-1.5" />
                    Doc
                  </TabsTrigger>
                </TabsList>
                <TabsContent value="code" className="p-3 pt-2">
                  <CodeBlock code={SAMPLE_CODE} language="python">
                    <CodeBlockHeader>
                      <CodeBlockTitle>dijkstra.py</CodeBlockTitle>
                      <CodeBlockCopyButton />
                    </CodeBlockHeader>
                  </CodeBlock>
                </TabsContent>
                <TabsContent value="html" className="p-3 pt-2">
                  <JSXPreview code={SAMPLE_HTML}>
                    <JSXPreviewContent />
                  </JSXPreview>
                </TabsContent>
                <TabsContent value="doc" className="p-3 pt-2">
                  <CodeBlock code={SAMPLE_DOC} language="markdown">
                    <CodeBlockHeader>
                      <CodeBlockTitle>README.md</CodeBlockTitle>
                      <CodeBlockCopyButton />
                    </CodeBlockHeader>
                  </CodeBlock>
                </TabsContent>
              </Tabs>
            </ArtifactContent>
          </Artifact>

          {/* Web preview of HTML artifact */}
          <div className="space-y-2">
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
              <EyeIcon size={12} />
              Live preview
            </h2>
            <WebPreview defaultUrl="https://agentic-os-phi-kohl.vercel.app" className="rounded-2xl border border-border overflow-hidden bg-card">
              <WebPreviewNavigation className="border-b border-border bg-muted/30 px-3 py-2 flex items-center gap-2">
                <WebPreviewNavigationButton tooltip="Back" disabled>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <path d="M9 2L4 7L9 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                  </svg>
                </WebPreviewNavigationButton>
                <WebPreviewNavigationButton tooltip="Forward" disabled>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <path d="M5 2L10 7L5 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                  </svg>
                </WebPreviewNavigationButton>
                <WebPreviewNavigationButton tooltip="Reload">
                  <RefreshCwIcon size={13} />
                </WebPreviewNavigationButton>
                <WebPreviewUrl value="https://agentic-os-phi-kohl.vercel.app" readOnly className="flex-1" />
                <WebPreviewNavigationButton tooltip="Open in new tab">
                  <ExternalLinkIcon size={13} />
                </WebPreviewNavigationButton>
              </WebPreviewNavigation>
              <WebPreviewBody src="https://agentic-os-phi-kohl.vercel.app" className="h-72 bg-background" />
            </WebPreview>
          </div>

          {/* Environment Variables */}
          <div>
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <SparklesIcon size={12} />
              Environment Variables
            </h2>
            <EnvironmentVariables className="rounded-2xl border border-border bg-card overflow-hidden">
              <EnvironmentVariablesHeader className="p-3 border-b border-border flex items-center justify-between">
                <EnvironmentVariablesTitle className="text-sm font-semibold">
                  Production secrets
                </EnvironmentVariablesTitle>
                <button
                  onClick={() => setShowEnv((v) => !v)}
                  className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  {showEnv ? "Hide" : "Reveal"}
                </button>
              </EnvironmentVariablesHeader>
              <EnvironmentVariablesContent className="p-2">
                {ENV_VARS.map((v) => (
                  <EnvironmentVariable
                    key={v.name}
                    name={v.name}
                    value={v.value}
                    readOnly
                    revealed={showEnv}
                    className="p-2 rounded-lg hover:bg-muted/50"
                  >
                    <EnvironmentVariableCopyButton />
                  </EnvironmentVariable>
                ))}
              </EnvironmentVariablesContent>
            </EnvironmentVariables>
          </div>

          {/* API schema */}
          <div>
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
              API Reference
            </h2>
            <SchemaDisplay
              method="POST"
              path="/api/chat"
              description="Stream a chat completion with chain-of-thought reasoning"
              className="rounded-2xl border border-border bg-card overflow-hidden"
            >
              <SchemaDisplayHeader className="p-3 border-b border-border">
                <div className="flex items-center gap-2 flex-wrap">
                  <SchemaDisplayMethod className="px-2 py-0.5 rounded text-[10px] font-bold bg-teal/10 text-teal border border-teal/20">
                    POST
                  </SchemaDisplayMethod>
                  <SchemaDisplayPath className="text-sm font-mono" />
                </div>
                <SchemaDisplayDescription className="text-xs text-muted-foreground mt-1.5" />
              </SchemaDisplayHeader>
              <SchemaDisplayContent className="p-3 space-y-3">
                <SchemaDisplayRequest>
                  <SchemaDisplayParameters>
                    <SchemaDisplayParameter name="messages" type="Message[]" required>
                      Array of conversation messages with role and content
                    </SchemaDisplayParameter>
                    <SchemaDisplayParameter name="model" type="string" default="MiniMax-M2">
                      The model ID to use
                    </SchemaDisplayParameter>
                  </SchemaDisplayParameters>
                </SchemaDisplayRequest>
                <SchemaDisplayResponse status="200" description="Streamed NDJSON response">
                  <SchemaDisplayBody mediaType="application/x-ndjson" />
                </SchemaDisplayResponse>
              </SchemaDisplayContent>
            </SchemaDisplay>
          </div>

          {/* Commit history */}
          <div>
            <h2 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <GitBranchIcon size={12} />
              Recent commits
            </h2>
            <div className="space-y-2">
              {COMMITS.map((c) => (
                <Commit key={c.hash} className="rounded-2xl border border-border bg-card p-3">
                  <CommitHeader className="flex items-start gap-3">
                    <CommitAuthorAvatar
                      initials={c.initials}
                      className="w-8 h-8 rounded-full bg-gradient-to-br from-teal to-coral flex items-center justify-center text-white text-xs font-semibold flex-shrink-0"
                    >
                      {c.initials}
                    </CommitAuthorAvatar>
                    <div className="flex-1 min-w-0">
                      <CommitInfo className="flex items-center gap-2 flex-wrap">
                        <CommitAuthor className="text-xs font-medium">{c.author}</CommitAuthor>
                        <CommitHash className="text-[10px] font-mono text-muted-foreground">
                          {c.hash.slice(0, 7)}
                        </CommitHash>
                        <CommitTimestamp
                          date={new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)}
                          className="text-[10px] text-muted-foreground"
                        >
                          · {c.time}
                        </CommitTimestamp>
                      </CommitInfo>
                      <CommitMessage className="text-sm mt-1">{c.message}</CommitMessage>
                    </div>
                    <CommitActions>
                      <CommitCopyButton hash={c.hash} />
                    </CommitActions>
                  </CommitHeader>
                  <CommitContent className="mt-2 ml-11">
                    <CommitFiles>
                      {c.files.map((f) => (
                        <CommitFile
                          key={f.name}
                          filename={f.name}
                          additions={f.additions}
                          deletions={f.deletions}
                          className="text-[10px] flex items-center gap-2 py-0.5"
                        />
                      ))}
                    </CommitFiles>
                  </CommitContent>
                </Commit>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
